import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { MyContextProvider } from './context/Context'
import ProductLogo from './pages/Components/logoComp/ProductLogo'
import HeaderText from './pages/Components/headerComp/HeaderText'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='background px-20 py-10'>
          <ProductLogo />
          <MyContextProvider>
            {children}
          </MyContextProvider>
        </div>

      </body>
    </html>
  )
}
